from BTree import BTree 
from PalabraDocumentos import PalabraDocumentos

arbol = BTree(3)
# arbol.insertar('untref')
# arbol.insertar('computacion')
# arbol.insertar('ingenieria')
# for i in range(20)
arbol.insertar(PalabraDocumentos('untref', ['link']))
arbol.insertar(PalabraDocumentos('computacion', ['link 2']))
arbol.insertar(PalabraDocumentos('ingenieria', ['link 3']))
arbol.insertar(PalabraDocumentos('gato', ['link 4']))
arbol.insertar(PalabraDocumentos('perro', ['link 5']))
arbol.insertar(PalabraDocumentos('muntref', ['link']))
arbol.insertar(PalabraDocumentos('computadora', ['link 2']))
arbol.insertar(PalabraDocumentos('ingeniero', ['link 3']))
arbol.insertar(PalabraDocumentos('gata', ['link 4']))
arbol.insertar(PalabraDocumentos('perra', ['link 5']))
arbol.insertar(PalabraDocumentos('xuntref', ['link']))
arbol.insertar(PalabraDocumentos('computo', ['link 2']))
arbol.insertar(PalabraDocumentos('ingeniera', ['link 3']))
arbol.insertar(PalabraDocumentos('garra', ['link 4']))
arbol.insertar(PalabraDocumentos('perrera', ['link 5']))
# arbol.insertar(3)
# arbol.insertar(4)
# arbol.insertar(2)
# arbol.insertar(1)
# arbol.insertar(15)
# arbol.insertar(57)
# arbol.insertar(52)
# arbol.insertar(24)
# arbol.insertar(0)

arbol.print_order()